[profile.default]
src = "src"
test = "test"
out = "out"
libs = ["lib"]
solc_version = "0.8.26"
optimizer = true
optimizer_runs = 200
evm_version = "cancun"

[profile.default.fmt]
line_length = 120
tab_width = 4

[etherscan]
# example:
# mainnet = { key = "${ETHERSCAN_API_KEY}" }
